appcore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('modules.api.urls', namespace='api')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

modules/api/urls.py
from django.urls import path
from modules.api import views
from django.views.generic.base import TemplateView

app_name = 'api'

urlpatterns = [
	path('', TemplateView.as_view(template_name='home.html'), name='home'),
	path('monday_redirect/',views.redirectMondayView.as_view(), name='redirect_monday'),
	path('logout/', views.Logout.as_view(), name='logout'),
	path('item_list/', views.ListItems.as_view(), name='item_list'),
	path('create_item/', views.CreateItem.as_view(), name='create_item'),
	
	path('item_create/', views.ItemCreate.as_view(), name='item_create'),
	path('create_subitem/', views.SubitemCreate.as_view(), name='create_subitem'),
	path('update_item/<int:id>', views.ItemUpdate.as_view(), name='update_item'),
	path('delete_item/<int:id>', views.ItemDelete.as_view(), name='delete_item'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{% block title %}{% endblock title %}</title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
	{% block styles %}
	{% endblock styles %}
</head>
<body style="font-family:'Montserrat', sans-serif;">
	{% block content %}
	{% endblock %}
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
	{% block script %}
	{% endblock script %}
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% block title %}
	Home
{% endblock title %}
{% block content %}
	<div class="container my-5 text-center">
		{% if user.is_authenticated %}
			<h3>Welcome {{user.first_name}}</h3>
			<a href="{% url 'api:logout' %}" class="btn btn-danger my-4 fw-bold">Logout</a>
		{% else %}
			<a href="https://auth.monday.com/oauth2/authorize?client_id=726fa380a2e062c4d31b3b6c2a915ef6" class="btn btn-primary fw-bold">Login with Monday</a>
		{% endif %}
	</div>
{% endblock %}

templates/profile.html
{% extends 'base.html' %}
{% block title %}
Profile
{% endblock title %}
{% block content %}
<div class="container my-5">
	<div class="row d-flex justify-content-center ">
		<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 bg-light shadow text-center">
			<img src="{% if user.data.me.photo_original %}{{user.data.me.photo_original.url}}{% endif %}" class="rounded-circle">
			<h2>{{user.data.me.name}}</h2>
			<h5>Email: {{user.data.me.email}}</h5>
			<h6>Phone:{% if not user.data.me.phone %}None{% else %} {{user.data.me.phone}}{% endif %}</h6>
			<h6>Location: {{user.data.me.location}}</h6>
			<h6>Account Id: {{user.account_id}}</h6>
			<h6>Id: {{user.data.me.id}}</h6>
			<h6>Is admin: {{user.data.me.is_admin}}</h6>
			<h6>Is guest: {{user.data.me.is_guest}}</h6>
		</div>
	</div>
</div>
{% endblock %}